export type LocalizedText = { zh: string; en: string };

const labels: Record<string, LocalizedText> = {
  "Sidecar-compatible Mac and display": { zh: "兼容 Sidecar 的 Mac 和显示器", en: "Sidecar-compatible Mac and display" },
  "audio-output": { zh: "音频输出", en: "Audio output" },
  "built-in battery": { zh: "内建电池", en: "Built-in battery" },
  "connected display": { zh: "已连接的显示器", en: "Connected display" },
  "controllable system fans": { zh: "可控制的系统风扇", en: "Controllable system fans" },
  "keyboard": { zh: "键盘", en: "Keyboard" },
  "network-connection": { zh: "网络连接", en: "Network connection" },
  "active-audio-applications": { zh: "正在播放音频的应用", en: "Active audio applications" },
  "ai-prompt-content": { zh: "AI 提示内容", en: "AI prompt content" },
  "ai-requests": { zh: "AI 请求", en: "AI requests" },
  "application-audio-levels": { zh: "应用音量", en: "Application audio levels" },
  "application-windows": { zh: "应用窗口", en: "Application windows" },
  "audio-state": { zh: "音频状态", en: "Audio state" },
  "battery-state": { zh: "电池状态", en: "Battery state" },
  "calendar-events": { zh: "日历事件", en: "Calendar events" },
  "clipboard-content": { zh: "剪贴板内容", en: "Clipboard content" },
  "connected-device-battery-state": { zh: "已连接设备的电量", en: "Connected device battery state" },
  "connectivity-results": { zh: "连接测试结果", en: "Connectivity results" },
  "custom-test-targets": { zh: "自定义测试目标", en: "Custom test targets" },
  "developer-cache-paths": { zh: "开发缓存路径", en: "Developer cache paths" },
  "display-state": { zh: "显示器状态", en: "Display state" },
  "file-sizes": { zh: "文件大小", en: "File sizes" },
  "filesystem-paths": { zh: "文件系统路径", en: "Filesystem paths" },
  "foreground-application": { zh: "前台应用", en: "Foreground application" },
  "frontmost-application": { zh: "最前方应用", en: "Frontmost application" },
  "input-device-availability": { zh: "输入设备可用状态", en: "Input device availability" },
  "input-events": { zh: "输入事件", en: "Input events" },
  "input-source": { zh: "输入法", en: "Input source" },
  "installed-applications": { zh: "已安装的应用", en: "Installed applications" },
  "local-cli-credentials": { zh: "本机 CLI 凭据", en: "Local CLI credentials" },
  "local-keyword-input-when-enabled": { zh: "启用后的本机关键词输入", en: "Local keyword input when enabled" },
  "local-network-addresses": { zh: "本地网络地址", en: "Local network addresses" },
  "menu-bar-icon-images": { zh: "菜单栏图标图像", en: "Menu bar icon images" },
  "menu-bar-items": { zh: "菜单栏项目", en: "Menu bar items" },
  "monitoring-state": { zh: "监控状态", en: "Monitoring state" },
  "network-connection-state": { zh: "网络连接状态", en: "Network connection state" },
  "network-location": { zh: "网络位置", en: "Network location" },
  "output-volume": { zh: "输出音量", en: "Output volume" },
  "pointer-events": { zh: "指针事件", en: "Pointer events" },
  "productivity-state": { zh: "效率工具状态", en: "Productivity state" },
  "project-working-directories": { zh: "项目工作目录", en: "Project working directories" },
  "public-network-addresses": { zh: "公网地址", en: "Public network addresses" },
  "recognized-text-and-codes": { zh: "识别的文本与代码", en: "Recognized text and codes" },
  "running-applications": { zh: "运行中的应用", en: "Running applications" },
  "screen-pixels": { zh: "屏幕像素", en: "Screen pixels" },
  "screenshots": { zh: "截屏", en: "Screenshots" },
  "script-content": { zh: "脚本内容", en: "Script content" },
  "script-output": { zh: "脚本输出", en: "Script output" },
  "script-working-directories": { zh: "脚本工作目录", en: "Script working directories" },
  "selected-files": { zh: "所选文件", en: "Selected files" },
  "selected-text": { zh: "所选文本", en: "Selected text" },
  "shell-configuration": { zh: "Shell 配置", en: "Shell configuration" },
  "shortcut-folders": { zh: "快捷指令文件夹", en: "Shortcut folders" },
  "shortcut-names": { zh: "快捷指令名称", en: "Shortcut names" },
  "siri-message-input": { zh: "Siri 消息输入", en: "Siri message input" },
  "siri-submission-state": { zh: "Siri 提交状态", en: "Siri submission state" },
  "storage-state": { zh: "存储状态", en: "Storage state" },
  "subscription-quota": { zh: "订阅额度", en: "Subscription quota" },
  "system-appearance": { zh: "系统外观", en: "System appearance" },
  "system-settings": { zh: "系统设置", en: "System settings" },
  "system-state": { zh: "系统状态", en: "System state" },
  "translation-requests": { zh: "翻译请求", en: "Translation requests" },
  "upload-configuration": { zh: "上传配置", en: "Upload configuration" },
  "usage-statistics": { zh: "使用统计", en: "Usage statistics" },
  "wifi-signal": { zh: "Wi-Fi 信号", en: "Wi-Fi signal" },
  "window-frames": { zh: "窗口位置与大小", en: "Window frames" },
  "window-geometry": { zh: "窗口布局", en: "Window geometry" },
  "window-titles": { zh: "窗口标题", en: "Window titles" },
  "application-identifiers": { zh: "应用标识", en: "Application identifiers" },
  "cached-network-state": { zh: "缓存的网络状态", en: "Cached network state" },
  "cleanup-audit-history": { zh: "清理审计历史", en: "Cleanup audit history" },
  "cleanup-staging-journal": { zh: "清理暂存记录", en: "Cleanup staging journal" },
  "coding-session-statistics": { zh: "编程会话统计", en: "Coding session statistics" },
  "encrypted-clipboard-history": { zh: "加密的剪贴板历史", en: "Encrypted clipboard history" },
  "local-encryption-key": { zh: "本机加密密钥", en: "Local encryption key" },
  "menu-bar-item-layout": { zh: "菜单栏项目布局", en: "Menu bar item layout" },
  "performance-history": { zh: "性能历史", en: "Performance history" },
  "pinned-settings": { zh: "置顶设置", en: "Pinned settings" },
  "plugin-configuration": { zh: "插件配置", en: "Plugin configuration" },
  "preferred-volume-levels": { zh: "音量偏好", en: "Preferred volume levels" },
  "privacy-display-preference": { zh: "隐私显示偏好", en: "Privacy display preference" },
  "scan-result-cache": { zh: "扫描结果缓存", en: "Scan result cache" },
  "setting-change-history": { zh: "设置更改历史", en: "Setting change history" },
  "settings-profiles": { zh: "设置方案", en: "Settings profiles" },
  "shell-configuration-backup": { zh: "Shell 配置备份", en: "Shell configuration backup" },
  "shortcut-bindings": { zh: "快捷键绑定", en: "Shortcut bindings" },
  "switcher-configuration": { zh: "切换器配置", en: "Switcher configuration" },
  "user-exported-recordings": { zh: "用户导出的录制", en: "User-exported recordings" },
  "user-exported-screenshots": { zh: "用户导出的截屏", en: "User-exported screenshots" },
  "full-disk-access": { zh: "完全磁盘访问权限", en: "Full Disk Access" },
  accessibility: { zh: "辅助功能", en: "Accessibility" },
  automation: { zh: "自动化", en: "Automation" },
  calendarFullAccess: { zh: "完整日历访问", en: "Full Calendar Access" },
  inputMonitoring: { zh: "输入监控", en: "Input Monitoring" },
  "screen-recording": { zh: "屏幕录制", en: "Screen Recording" },
  "system-audio-recording": { zh: "系统音频录制", en: "System Audio Recording" },
  "unified-search": { zh: "统一搜索", en: "Unified Search" },
  "global-shortcut": { zh: "全局快捷键", en: "Global Shortcut" },
  "run-link": { zh: "运行链接", en: "Run Link" },
  workflow: { zh: "工作流", en: "Workflow" },
  "automatic-rule": { zh: "自动规则", en: "Automatic Rule" },
  "action-grid": { zh: "操作面板", en: "Action Grid" },
  "trackpad-gesture": { zh: "触控板手势", en: "Trackpad Gesture" },
  "app-intent": { zh: "App Intent", en: "App Intent" },
  manual: { zh: "手动", en: "Manual" },
  safe: { zh: "安全", en: "Safe" },
  confirmationRequired: { zh: "需要确认", en: "Confirmation Required" },
  none: { zh: "无", en: "None" },
  simple: { zh: "简单", en: "Simple" },
  guided: { zh: "引导式", en: "Guided" },
  advanced: { zh: "高级", en: "Advanced" },
  optional: { zh: "可选", en: "Optional" },
  required: { zh: "必需", en: "Required" },
  session: { zh: "会话期间", en: "Session" },
  "until-disabled": { zh: "直到停用", en: "Until disabled" },
  "until-uninstalled": { zh: "直到卸载", en: "Until uninstalled" },
  "user-controlled": { zh: "由用户控制", en: "User-controlled" },
};

export function localizedToken(token: string): LocalizedText {
  return labels[token] ?? { zh: token, en: token };
}

export function localizedTokenList(tokens: string[]): LocalizedText {
  return {
    zh: tokens.map((token) => localizedToken(token).zh).join("、"),
    en: tokens.map((token) => localizedToken(token).en).join(", "),
  };
}
